name: couchify
description: A Couchbase Lite API for Flutter developers.
version: 0.1.0
homepage: https://github.com/ManulGoyal/couchify
repository: https://github.com/ManulGoyal/couchify
platforms:
  android:

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

  uuid: 3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

  pigeon: ^1.0.12

flutter:
  plugin:
    platforms:
      android:
        package: com.manul.couchify
        pluginClass: CouchifyPlugin
      ios:
        pluginClass: CouchifyPlugin
